name: Build the project
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get project code
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: run unit tests
        run: npm test
      - name: output Github context
        run: echo "${{ github.event.action }}"
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: get project code
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
  bump-version:
    name: Bump Version & Create GitHub Tag
    runs-on: ubuntu-latest
    needs: [test, build]
    if:  ${{ github.event.action == 'opened' || github.event.action == 'review_requested' }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
          skip-tag:  'true'
          major-wording: 'MAJOR'
          minor-wording: 'MINOR'